FROM debian10

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

COPY ./requirements.txt /Disconym/requirements.txt

WORKDIR /Disconym

RUN pip install -r requirements.txt

COPY . /Disconym

ENTRYPOINT [ "python" ]

CMD [ "api_server.py" ]